using System.Net;
using System.Reflection;
using System.Text;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using Npgsql;
using ToonSpeaker.Api.Application;
using ToonSpeaker.Api.Domain;
using ToonSpeaker.Api.Infrastructure.Persistence;
using ToonSpeaker.Api.Infrastructure.Services;

var builder = WebApplication.CreateBuilder(args);

// ─── Forwarded headers (Render / Cloudflare terminate TLS at the edge) ───────
// Makes Request.IsHttps correct inside the container.
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

// ─── MVC / JSON ───────────────────────────────────────────────────────────────
// UseSystemTextJson with JsonStringEnumConverter: ContentType renders as "Series"/"Movie" not 0/1
builder.Services.AddControllers()
    .AddJsonOptions(o => o.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddProblemDetails();
builder.Services.AddMemoryCache();

// ─── Swagger ──────────────────────────────────────────────────────────────────
builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title       = "AniSpeaker API",
        Version     = "v1",
        Description = "Backend API for AniSpeaker — anime / cartoon / movie streaming platform."
    });

    // Wire in XML doc comments generated by <GenerateDocumentationFile>
    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
    if (File.Exists(xmlPath))
        options.IncludeXmlComments(xmlPath);

    // Bearer token auth for protected endpoints
    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Name        = "Authorization",
        Type        = SecuritySchemeType.Http,
        Scheme      = "bearer",
        BearerFormat = "JWT",
        In          = ParameterLocation.Header,
        Description = "Paste a JWT access token to authorize protected endpoints."
    });
    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
            },
            Array.Empty<string>()
        }
    });
});

// ─── Database ─────────────────────────────────────────────────────────────────
var connectionString = ToNpgsqlConnectionString(builder.Configuration.GetConnectionString("Default"));
builder.Services.AddDbContext<AppDbContext>(options => options.UseNpgsql(connectionString));

// ─── Identity ─────────────────────────────────────────────────────────────────
builder.Services.AddIdentityCore<AppUser>(options =>
    {
        options.Password.RequiredLength = 8;
        options.User.RequireUniqueEmail = true;
    })
    .AddRoles<IdentityRole<Guid>>()
    .AddEntityFrameworkStores<AppDbContext>()
    .AddSignInManager()
    .AddDefaultTokenProviders();

// ─── JWT ──────────────────────────────────────────────────────────────────────
var jwt = builder.Configuration.GetSection("Jwt").Get<JwtOptions>() ?? new JwtOptions();
if (jwt.Secret.Length < 32)
    throw new InvalidOperationException(
        "Jwt:Secret must be at least 32 characters. Set Jwt__Secret in Render environment variables.");
builder.Services.AddSingleton(jwt);

// ─── Application services ─────────────────────────────────────────────────────
builder.Services.AddSingleton<TokenService>();
builder.Services.AddScoped<IContentService, ContentService>();
builder.Services.AddScoped<CatalogDocumentService>();

// ─── Authentication ───────────────────────────────────────────────────────────
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.MapInboundClaims = false;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer           = true,
            ValidIssuer              = jwt.Issuer,
            ValidateAudience         = true,
            ValidAudience            = jwt.Audience,
            ValidateIssuerSigningKey = true,
            IssuerSigningKey         = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwt.Secret)),
            ValidateLifetime         = true,
            ClockSkew                = TimeSpan.FromSeconds(30),
            RoleClaimType            = "role",
            NameClaimType            = "sub"
        };
    });
builder.Services.AddAuthorization();

// ─── CORS ─────────────────────────────────────────────────────────────────────
// Override on Render: Cors__AllowedOrigins__0=https://anispeaker.pages.dev
var allowedOrigins = builder.Configuration.GetSection("Cors:AllowedOrigins").Get<string[]>()
    ?? ["http://localhost:4200"];

builder.Services.AddCors(options =>
    options.AddPolicy("Frontend", policy => policy
        .WithOrigins(allowedOrigins)
        .AllowAnyHeader()
        .AllowAnyMethod()
        .AllowCredentials()));

// ═════════════════════════════════════════════════════════════════════════════
var app = builder.Build();
// ═════════════════════════════════════════════════════════════════════════════

// ForwardedHeaders must come first — makes Request.IsHttps correct for all subsequent middleware.
app.UseForwardedHeaders();

// Return JSON ProblemDetails on unhandled exceptions instead of an empty 500 body.
app.UseExceptionHandler(errorApp => errorApp.Run(async context =>
{
    context.Response.StatusCode  = (int)HttpStatusCode.InternalServerError;
    context.Response.ContentType = "application/problem+json";

    var feature = context.Features.Get<Microsoft.AspNetCore.Diagnostics.IExceptionHandlerPathFeature>();
    var error   = feature?.Error;

    var logger = context.RequestServices.GetRequiredService<ILogger<Program>>();
    logger.LogError(error, "Unhandled exception on {Method} {Path}", context.Request.Method, context.Request.Path);

    var detail = app.Environment.IsDevelopment() ? error?.ToString() : "An unexpected error occurred.";
    await context.Response.WriteAsJsonAsync(new
    {
        type   = "https://httpstatuses.io/500",
        title  = "Internal Server Error",
        status = 500,
        detail
    });
}));

// NOTE: No UseHttpsRedirection — Render/Cloudflare terminate TLS at the edge.
// The container listens on plain HTTP port 8080; adding UseHttpsRedirection
// here caused an infinite redirect loop.

app.UseSwagger();
app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "AniSpeaker API v1"));

app.UseCors("Frontend");
app.UseAuthentication();
app.UseAuthorization();

app.MapGet("/", () => Results.Ok(new { name = "AniSpeaker API", version = "v1", status = "running", docs = "/swagger" }));
app.MapControllers();

// ─── Database migrations ──────────────────────────────────────────────────────
// Enable on Render first deploy via: Database__ApplyMigrations=true
// Remove the env var after migrations succeed (or leave it — MigrateAsync is idempotent).
if (app.Configuration.GetValue<bool>("Database:ApplyMigrations"))
{
    using var scope = app.Services.CreateScope();
    var db          = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    var userManager = scope.ServiceProvider.GetRequiredService<UserManager<AppUser>>();
    try
    {
        await db.Database.MigrateAsync();
        app.Logger.LogInformation("Database migrations are up to date.");
        await db.Database.ExecuteSqlRawAsync(
            "ALTER TABLE \"Content\" ADD COLUMN IF NOT EXISTS \"CatalogJson\" jsonb;");
        await db.Database.ExecuteSqlRawAsync(
            "ALTER TABLE \"VideoSources\" ADD COLUMN IF NOT EXISTS \"EmbedType\" varchar(20) NOT NULL DEFAULT 'Iframe';");

        // Seed initial categories if table is empty
        if (!await db.Categories.AnyAsync())
        {
            db.Categories.AddRange(
                new Category { Name = "Action",    Slug = "action",    SortOrder = 1 },
                new Category { Name = "Adventure", Slug = "adventure", SortOrder = 2 },
                new Category { Name = "Comedy",    Slug = "comedy",    SortOrder = 3 },
                new Category { Name = "Fantasy",   Slug = "fantasy",   SortOrder = 4 },
                new Category { Name = "Sci-Fi",    Slug = "sci-fi",    SortOrder = 5 }
            );
            await db.SaveChangesAsync();
            app.Logger.LogInformation("Seeded default categories.");
        }

        if (app.Configuration.GetValue<bool>("Database:BackfillCatalog"))
        {
            var catalog = scope.ServiceProvider.GetRequiredService<CatalogDocumentService>();
            var missingDocuments = await db.Content.Where(x => x.CatalogJson == null).Select(x => x.Id).ToListAsync();
            foreach (var contentId in missingDocuments)
                await catalog.SyncAsync(contentId, CancellationToken.None);
            if (missingDocuments.Count > 0)
                app.Logger.LogInformation("Backfilled {Count} catalog JSON documents.", missingDocuments.Count);
        }

        // Ensure default admin user exists
        var adminEmail = "admin@anispeaker.com";
        var adminUser  = await userManager.FindByEmailAsync(adminEmail);
        if (adminUser is null)
        {
            adminUser = new AppUser
            {
                UserName       = adminEmail,
                Email          = adminEmail,
                DisplayName    = "AniSpeaker Admin",
                Role           = "Admin",
                EmailConfirmed = true
            };
            var createRes = await userManager.CreateAsync(adminUser, "Admin@123456");
            if (createRes.Succeeded)
                app.Logger.LogInformation("Created default admin user: {Email} (Password: Admin@123456)", adminEmail);
        }
        else if (adminUser.Role != "Admin")
        {
            adminUser.Role = "Admin";
            await userManager.UpdateAsync(adminUser);
            app.Logger.LogInformation("Updated user {Email} role to Admin.", adminEmail);
        }
    }
    catch (Exception ex)
    {
        app.Logger.LogCritical(ex,
            "Database migration failed. Verify ConnectionStrings__Default is set correctly in Render " +
            "and that the Neon database is accessible.");
        throw;
    }
}

app.Run();

// ─── Helpers ──────────────────────────────────────────────────────────────────
static string ToNpgsqlConnectionString(string? configuredValue)
{
    if (string.IsNullOrWhiteSpace(configuredValue))
        throw new InvalidOperationException(
            "ConnectionStrings:Default is required. Set ConnectionStrings__Default in Render to the " +
            "Neon PostgreSQL connection string (postgres://user:pass@host/db?sslmode=require).");

    // Already a key=value Npgsql string — pass through unchanged.
    if (!Uri.TryCreate(configuredValue, UriKind.Absolute, out var uri) ||
        (uri.Scheme is not "postgres" and not "postgresql"))
        return configuredValue;

    // Parse a postgres:// URL from the Neon dashboard into Npgsql key=value format.
    var userInfo = uri.UserInfo.Split(':', 2);
    var database = Uri.UnescapeDataString(uri.AbsolutePath.Trim('/'));
    if (userInfo.Length != 2 || string.IsNullOrWhiteSpace(uri.Host) || string.IsNullOrWhiteSpace(database))
        throw new InvalidOperationException("ConnectionStrings:Default contains an invalid PostgreSQL URL.");

    var npgsql = new NpgsqlConnectionStringBuilder
    {
        Host     = uri.Host,
        Port     = uri.IsDefaultPort ? 5432 : uri.Port,
        Database = database,
        Username = Uri.UnescapeDataString(userInfo[0]),
        Password = Uri.UnescapeDataString(userInfo[1])
    };

    // Forward query params — map postgres URL param names to Npgsql key=value names.
    foreach (var pair in uri.Query.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries))
    {
        var kv     = pair.Split('=', 2);
        var rawKey = Uri.UnescapeDataString(kv[0]);
        var value  = kv.Length == 2 ? Uri.UnescapeDataString(kv[1]) : string.Empty;

        var npgsqlKey = rawKey.ToLowerInvariant() switch
        {
            "sslmode"         => "SSL Mode",
            "channel_binding" => "Channel Binding",
            _                 => rawKey
        };

        npgsql[npgsqlKey] = value;
    }

    return npgsql.ConnectionString;
}

public partial class Program;
