import { Routes } from '@angular/router';
import { Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AdminService, Category, SaveContent, Season } from '../../core/services/admin.service';
import { ApiContent } from '../../models/content.model';
@Component({ standalone: true, imports: [FormsModule], templateUrl: './admin.component.html', styleUrl: './admin.component.scss' })
export class AdminComponent implements OnInit {
  api = inject(AdminService); categories: Category[] = []; content: ApiContent[] = []; section: 'dashboard' | 'categories' | 'content' | 'new' | 'uploads' = 'dashboard'; error = ''; notice = ''; uploading = false;
  category = { name: '', slug: '', sortOrder: 0 }; selectedContentId = ''; seasons: Season[] = []; videoKey = ''; form: SaveContent = { categoryId: '', title: '', slug: '', type: 'Series', description: null, posterUrl: null, bannerUrl: null, tags: [], published: true }; season = { number: 1, title: 'Season 1' }; episode = { number: 1, title: '', videoKey: '', thumbnailUrl: null as string | null, durationSeconds: 0, published: true };
  ngOnInit(): void { this.reload(); } reload(): void { this.api.categories().subscribe({ next: x => { this.categories = x; if (!this.form.categoryId && x[0]) this.form.categoryId = x[0].id; }, error: () => this.error = 'Could not load admin data. Confirm this account has the Admin role.' }); this.api.content().subscribe({ next: x => this.content = x.items }); }
  createCategory(): void { this.api.createCategory(this.category).subscribe({ next: () => { this.category = { name: '', slug: '', sortOrder: this.categories.length }; this.reload(); }, error: () => this.error = 'Could not create category.' }); }
  deleteCategory(id: string): void { if (confirm('Delete this category?')) this.api.deleteCategory(id).subscribe({ next: () => this.reload() }); }
  saveContent(): void { this.form.slug ||= this.form.title.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''); this.form.tags = typeof this.form.tags === 'string' ? (this.form.tags as unknown as string).split(',').map(x => x.trim()).filter(Boolean) : this.form.tags; this.api.createContent(this.form).subscribe({ next: x => { this.selectedContentId = x.id; this.notice = 'Content created. Add a season and episode below.'; this.reload(); }, error: () => this.error = 'Could not save content.' }); }
  addSeason(): void { if (!this.selectedContentId) return; this.api.createSeason(this.selectedContentId, this.season).subscribe({ next: x => { this.seasons.push(x); this.notice = 'Season added.'; }, error: () => this.error = 'Could not add season.' }); }
  addEpisode(seasonId: string): void { this.episode.videoKey = this.videoKey; if (!this.episode.videoKey) { this.error = 'Upload a video first.'; return; } this.api.createEpisode(seasonId, this.episode).subscribe({ next: () => { this.notice = 'Episode added.'; this.episode = { number: this.episode.number + 1, title: '', videoKey: '', thumbnailUrl: null, durationSeconds: 0, published: true }; }, error: () => this.error = 'Could not add episode.' }); }
  toggle(item: ApiContent): void { this.api.updateContent(item.id, { ...item, tags: item.tags, published: !item.published }).subscribe({ next: () => this.reload() }); }
  remove(item: ApiContent): void { if (confirm(`Delete ${item.title}?`)) this.api.deleteContent(item.id).subscribe({ next: () => this.reload() }); }
  upload(event: Event): void { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; this.uploading = true; this.api.initUpload(file, file.type.startsWith('video/') ? 'videos' : 'images').subscribe({ next: init => { const xhr = new XMLHttpRequest(); xhr.open('PUT', init.uploadUrl); xhr.setRequestHeader('Content-Type', file.type); xhr.onload = () => { this.uploading = false; if (xhr.status < 300) { if (file.type.startsWith('video/')) this.videoKey = init.objectKey; else this.form.posterUrl = init.publicUrl; this.notice = 'Upload complete.'; } else this.error = 'Storage upload failed.'; }; xhr.onerror = () => { this.uploading = false; this.error = 'Storage upload failed.'; }; xhr.send(file); }, error: () => { this.uploading = false; this.error = 'Could not start upload.'; } }); }
}
export const ADMIN_ROUTES: Routes = [{ path: '', component: AdminComponent }];
